name: telecaller_mobile_app
description: "MedTrac Pro - Homeopathy Medicine Distribution Telecaller App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  hive_flutter: ^1.1.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  intl: ^0.20.2
  csv: ^6.0.0
  share_plus: ^9.0.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.0
  firebase_messaging: ^15.0.0
  googleapis_auth: ^1.6.0
  flutter_local_notifications: ^17.2.1
  firebase_auth: ^5.1.1
  flutter_secure_storage: ^9.2.2
  geolocator: ^12.0.0
  flutter_background_service: ^5.0.7
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  image_picker: ^1.1.2
  fl_chart: ^0.69.0
  cached_network_image: ^3.3.0
  pdf: ^3.11.1
  battery_plus: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
